service: santPacia3ImageUpload

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : BucketSantPacia3
            - "/*"

functions:
  santPacia3ImageUpload:
    handler: handler.esp32S3ImageUpload
    events:
      - http:
          path: capture
          method: post
    environment:
      SLACK_TOKEN: ${ssm:santPacia3SlackToken}

resources:
 Resources:
   BucketSantPacia3:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: sant-pacia-3 
